/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_modification_ (void);
GtkWidget* create_fenetre_suppression_ (void);
GtkWidget* create_fenetre_select_region (void);
GtkWidget* create_fenetre_aff_cap (void);
GtkWidget* create_authpage (void);
GtkWidget* create_Admin (void);
GtkWidget* create_adminuseradddonor (void);
GtkWidget* create_window_don (void);
GtkWidget* create_windowAjout_don (void);
GtkWidget* create_windowModif_don (void);
GtkWidget* create_window2_don (void);
GtkWidget* create_result1 (void);
GtkWidget* create_result2 (void);
GtkWidget* create_result3 (void);
GtkWidget* create_result4 (void);
GtkWidget* create_GDPS (void);
GtkWidget* create_Affichage (void);
GtkWidget* create_resultat_recherche (void);
GtkWidget* create_result5 (void);
GtkWidget* create_static1 (void);
GtkWidget* create_indication (void);
GtkWidget* create_espaceinfirmier (void);
GtkWidget* create_contenufiltre (void);
GtkWidget* create_affichage_un_donneur (void);
GtkWidget* create_confirmationsuppression (void);
GtkWidget* create_modification (void);
