/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "gdps.h"
#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
 
  GtkWidget *Affichage;
  GtkWidget *espaceinfirmier;
  GtkWidget *contenufiltre;
  GtkWidget *affichage_un_donneur;
  GtkWidget *confirmationsuppression;
  GtkWidget *modification;


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*letype = create_letype ();
  gtk_widget_show (letype);
  laSurfacedeRecherche = create_laSurfacedeRecherche ();
  gtk_widget_show (laSurfacedeRecherche);
  lestypes = create_lestypes ();
  gtk_widget_show (lestypes);
  result1 = create_result1 ();
  gtk_widget_show (result1);
  result2 = create_result2 ();
  gtk_widget_show (result2);
  result3 = create_result3 ();
  gtk_widget_show (result3);
  result4 = create_result4 ();
  gtk_widget_show (result4);
  GDPS = create_GDPS ();
  gtk_widget_show (GDPS);*/
  Affichage = create_Affichage ();
  gtk_widget_show (Affichage);
gtk_widget_hide(Affichage);
  /*resultat_recherche = create_resultat_recherche ();
  gtk_widget_show (resultat_recherche);
  surface_recherche = create_surface_recherche ();
  gtk_widget_show (surface_recherche);*/
espaceinfirmier = create_espaceinfirmier ();
  gtk_window_set_position(GTK_WINDOW(espaceinfirmier),GTK_WIN_POS_CENTER);
  gtk_widget_show (espaceinfirmier);
  contenufiltre = create_contenufiltre ();
  gtk_widget_show (contenufiltre);
  affichage_un_donneur = create_affichage_un_donneur ();
  gtk_widget_show (affichage_un_donneur);
  confirmationsuppression = create_confirmationsuppression ();
  gtk_widget_show (confirmationsuppression);
  modification = create_modification ();
  gtk_widget_show (modification);

	gtk_widget_hide (contenufiltre);
gtk_widget_hide (espaceinfirmier);
	gtk_widget_hide (affichage_un_donneur);

	gtk_widget_hide (confirmationsuppression);

	gtk_widget_hide (modification);
//*********
GtkWidget* authpage = create_authpage ();
  gtk_widget_show (authpage);
  gtk_main ();
  return 0;
}

